// This Java file was generated by the TITAN Designer eclipse plug-in
// of the TTCN-3 Test Executor version CRL 113 200/6 R6A
// for (evdrapa@HU-00002036)

// Copyright (c) 2000-2019 Ericsson Telecom AB

/**
 * <code>org.eclipse.titan.titan_JavaTestPort_TCP_ASP.user_provided</code> package contains classes
 * that were written by the user, and contain the implementations of test ports and external functions, in the project titan.JavaTestPort.TCP_ASP.
 *<p>
 * Do not edit this file unless you know what you are doing!
 */
package org.eclipse.titan.titan_JavaTestPort_TCP_ASP.user_provided;

