#!/bin/sh

ln -s ../LibSip/xsd/http_uri_etsi_org_ngn_params_xml_comm_div_info.ttcn     .
ln -s ../LibSip/xsd/http_uri_etsi_org_ngn_params_xml_simservs_mcid.ttcn     .
ln -s ../LibSip/xsd/http_uri_etsi_org_ngn_params_xml_simservs_pstn.ttcn     .
ln -s ../LibSip/xsd/http_uri_etsi_org_ngn_params_xml_simservs_xcap.ttcn     .
ln -s ../LibSip/xsd/http_www_w3_org_XML_1998_namespace.ttcn     .
ln -s ../LibSip/xsd/NoTargetNamespace.ttcn     .
ln -s ../LibSip/xsd/urn_3gpp_ns_cw_1_0.ttcn     .
ln -s ../LibSip/xsd/urn_ietf_params_xml_ns_common_policy.ttcn     .
ln -s ../LibSip/xsd/urn_ietf_params_xml_ns_conference_info.ttcn     .
ln -s ../LibSip/xsd/urn_ietf_params_xml_ns_pidf_geopriv10_basicPolicy.ttcn     .
ln -s ../LibSip/xsd/urn_ietf_params_xml_ns_pidf_geopriv10.ttcn     .
ln -s ../LibSip/xsd/urn_ietf_params_xml_ns_pidf.ttcn     .
ln -s ../LibSip/xsd/urn_ietf_params_xml_ns_reginfo.ttcn     .
ln -s ../LibSip/xsd/urn_ietf_params_xml_ns_resource_lists.ttcn     .
ln -s ../LibSip/xsd/urn_oma_xml_xdm_common_policy.ttcn     .
ln -s ../LibSip/xsd/UsefulTtcn3Types.ttcn     .
ln -s ../LibSip/xsd/XSD.ttcn     .


ln -s ../LibCommon/LibCommon_AbstractData.ttcn     .
ln -s ../LibCommon/LibCommon_BasicTypesAndValues.ttcn     .
ln -s ../LibCommon/LibCommon_DataStrings.ttcn     .
ln -s ../LibCommon/LibCommon_Sync.ttcn     .
ln -s ../LibCommon/LibCommon_TextStrings.ttcn     .
ln -s ../LibCommon/LibCommon_Time.ttcn     .
ln -s ../LibCommon/LibCommon_VerdictControl.ttcn     .

ln -s ../LibSip/ttcn/LibSip_Interface.ttcn     .
ln -s ../LibSip/ttcn/LibSip_PIXITS.ttcn     .
ln -s ../LibSip/ttcn/LibSip_SDPTypes.ttcn     .
ln -s ../LibSip/ttcn/LibSip_SimpleMsgSummaryTypes.ttcn     .
ln -s ../LibSip/ttcn/LibSip_SIPTypesAndValues.ttcn     .
ln -s ../LibSip/ttcn/LibSip_SMSFunctions.ttcn     .
ln -s ../LibSip/ttcn/LibSip_SMSTemplates.ttcn     .
ln -s ../LibSip/ttcn/LibSip_SMSTypesAndValues.ttcn     .
ln -s ../LibSip/ttcn/LibSip_Steps.ttcn     .
ln -s ../LibSip/ttcn/LibSip_Templates.ttcn     .
ln -s ../LibSip/ttcn/LibSip_XMLTypes.ttcn     .







ln -s ../titan.ProtocolModules.SDP/src/lex.SDP_parse_.c .
ln -s ../titan.ProtocolModules.SDP/src/SDP_EncDec.cc    .
ln -s ../titan.ProtocolModules.SDP/src/SDP_parse_parser.h .
ln -s ../titan.ProtocolModules.SDP/src/SDP_parse_.tab.c  .
ln -s ../titan.ProtocolModules.SDP/src/SDP_parse_.tab.h  .
ln -s ../titan.ProtocolModules.SDP/src/SDP_Types.ttcn  .


ln -s ../titan.TestPorts.SIPmsg/src/lex.SIP_parse_.c .
ln -s ../titan.TestPorts.SIPmsg/src/SIPmsg_PortType.ttcn .
ln -s ../titan.TestPorts.SIPmsg/src/SIPmsg_PT.cc    .
ln -s ../titan.TestPorts.SIPmsg/src/SIPmsg_PT.hh    .
ln -s ../titan.TestPorts.SIPmsg/src/SIPmsg_Types.ttcn  .
ln -s ../titan.TestPorts.SIPmsg/src/SIP_parse.h  .
ln -s ../titan.TestPorts.SIPmsg/src/SIP_parse_.tab.h  .
ln -s ../titan.TestPorts.SIPmsg/src/SIP_parse_.tab.c  .

ln -s ../titan.ProtocolModules.MIME/src/MIME_EncDec.cc  .
ln -s ../titan.ProtocolModules.MIME/src/MIME_Types.ttcn  .
ln -s ../titan.ProtocolModules.MIME/src/MIME_parse.h  .
ln -s ../titan.ProtocolModules.MIME/src/MIME_parse.l  .
ln -s ../titan.ProtocolModules.MIME/src/MIME_parse.y  .
ln -s ../titan.ProtocolModules.MIME/src/MIME_parse_.tab.c  .
ln -s ../titan.ProtocolModules.MIME/src/MIME_parse_.tab.h  .
ln -s ../titan.ProtocolModules.MIME/src/lex.MIME_parse_.c  .


ln -s   ../titan.Libraries.TCCUsefulFunctions/src/TCCDateTime.cc .
ln -s   ../titan.Libraries.TCCUsefulFunctions/src/TCCDateTime_Functions.ttcn
ln -s   ../titan.Libraries.TCCUsefulFunctions/src/TCCConversion.cc .
ln -s   ../titan.Libraries.TCCUsefulFunctions/src/TCCConversion_Functions.ttcn
ln -s   ../titan.Libraries.TCCUsefulFunctions/src/TCCInterface.cc .
ln -s   ../titan.Libraries.TCCUsefulFunctions/src/TCCInterface_Functions.ttcn
ln -s   ../titan.Libraries.TCCUsefulFunctions/src/TCCInterface_ip.h





