#!/bin/sh
ln  -s TestPorts/SIPmsg/src/lex.SIP_parse_.c  .
ln  -s TestPorts/SIPmsg/src/SIPmsg_PortType.ttcn .
ln  -s TestPorts/SIPmsg/src/SIPmsg_PT.cc .
ln  -s TestPorts/SIPmsg/src/SIPmsg_PT.hh .
ln  -s TestPorts/SIPmsg/src/SIPmsg_Types.ttcn .
ln  -s TestPorts/SIPmsg/src/SIP_parse.h .
ln  -s TestPorts/SIPmsg/src/SIP_parse_.tab.c .
ln  -s TestPorts/SIPmsg/src/SIP_parse_.tab.h .


ln -s  Libraries/TCCUsefulFunctions/src/TCCDateTime.cc .
ln -s  Libraries/TCCUsefulFunctions/src/TCCDateTime_Functions.ttcn
ln -s  Libraries/TCCUsefulFunctions/src/TCCConversion.cc .
ln -s  Libraries/TCCUsefulFunctions/src/TCCConversion_Functions.ttcn
ln -s  Libraries/TCCUsefulFunctions/src/TCCInterface.cc .
ln -s  Libraries/TCCUsefulFunctions/src/TCCInterface_Functions.ttcn
ln -s  Libraries/TCCUsefulFunctions/src/TCCInterface_ip.h
